#!/bin/bash

set -o errexit

set -o nounset


worker_ready(){
    celery -A calendar_app_dev inspect ping
}

until worker_ready; do
    >&2 echo 'Celery workers not available :-('
    sleep 1

done
>&2 echo 'Celery workers are available and ready!...:-)'

flower \
    --app=calendar_app_dev \
    --broker="${CELERY_BROKER}"
