# Generated by Django 3.2.7 on 2022-08-15 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('description', models.TextField(blank=True, help_text='Describe Your Task Here.', verbose_name='Description')),
                ('priority', models.CharField(choices=[('eh', 'If I Had Time I Will Do That'), ('low', 'Need My Attention'), ('medium', 'Better Be Done In Time'), ('high', 'It Has To Be Done On Time'), ('life_depend', 'It Has To Be Done Or I Lose Something In My Life.')], default='medium', max_length=255, verbose_name='Priority')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
